apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          #image: gcr.io/clear-hulling-356517/backend_app_amitravel_image:latest
          image: gcr.io/optimistic-tube-357805/backend_app_amitravel_image:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
spec:
  selector:
    app: app-backend
  #type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
#---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: app-backend
#spec:
#  backend:
#    serviceName: app-backend
#    servicePort: 80
